// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Model.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<string>("City");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.Property<string>("Venue");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new { Id = new Guid("e4f70024-4e82-465c-9ad7-70d7407dafc9"), Category = "drinks", City = "London", Date = new DateTime(2021, 11, 27, 14, 26, 20, 887, DateTimeKind.Local), Description = "Activity 2 months ago", Title = "Past Activity 1", Venue = "Pub" },
                        new { Id = new Guid("cadcf63e-4d07-4ac1-8e62-ae5516b7ac26"), Category = "culture", City = "Paris", Date = new DateTime(2021, 12, 27, 14, 26, 20, 889, DateTimeKind.Local), Description = "Activity 1 month ago", Title = "Past Activity 2", Venue = "Louvre" },
                        new { Id = new Guid("07dd2b98-13bc-4ab1-a264-33904657ccdc"), Category = "culture", City = "London", Date = new DateTime(2022, 2, 27, 14, 26, 20, 889, DateTimeKind.Local), Description = "Activity 1 month in future", Title = "Future Activity 1", Venue = "Natural History Museum" },
                        new { Id = new Guid("e344fc47-3575-49cc-af12-a872ca482a5c"), Category = "music", City = "London", Date = new DateTime(2022, 3, 27, 14, 26, 20, 889, DateTimeKind.Local), Description = "Activity 2 months in future", Title = "Future Activity 2", Venue = "O2 Arena" },
                        new { Id = new Guid("8d6447f6-0d7f-4c57-9457-8b351826870a"), Category = "drinks", City = "London", Date = new DateTime(2022, 4, 27, 14, 26, 20, 889, DateTimeKind.Local), Description = "Activity 3 months in future", Title = "Future Activity 3", Venue = "Another pub" },
                        new { Id = new Guid("e914ee11-906e-46ba-a15e-4ffe2377ab34"), Category = "drinks", City = "London", Date = new DateTime(2022, 5, 27, 14, 26, 20, 889, DateTimeKind.Local), Description = "Activity 4 months in future", Title = "Future Activity 4", Venue = "Yet another pub" },
                        new { Id = new Guid("8cd87b22-1b08-4020-a25f-699c5e5ca9ec"), Category = "drinks", City = "London", Date = new DateTime(2022, 6, 27, 14, 26, 20, 889, DateTimeKind.Local), Description = "Activity 5 months in future", Title = "Future Activity 5", Venue = "Just another pub" },
                        new { Id = new Guid("2dad67b6-0e9a-451a-8edb-b8430380635f"), Category = "music", City = "London", Date = new DateTime(2022, 7, 27, 14, 26, 20, 889, DateTimeKind.Local), Description = "Activity 6 months in future", Title = "Future Activity 6", Venue = "Roundhouse Camden" },
                        new { Id = new Guid("2a69e10d-baf3-4291-a32a-99413f389029"), Category = "travel", City = "London", Date = new DateTime(2022, 8, 27, 14, 26, 20, 889, DateTimeKind.Local), Description = "Activity 2 months ago", Title = "Future Activity 7", Venue = "Somewhere on the Thames" },
                        new { Id = new Guid("54d1d7b8-3c40-4b39-9fb0-da91e792ea58"), Category = "film", City = "London", Date = new DateTime(2022, 9, 27, 14, 26, 20, 889, DateTimeKind.Local), Description = "Activity 8 months in future", Title = "Future Activity 8", Venue = "Cinema" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
